# Generated by Django 4.2.4 on 2023-08-27 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('time', models.CharField(max_length=200, null=True)),
                ('appointment_day', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dor', to=settings.AUTH_USER_MODEL)),
                ('medical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='core.medical')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='1234567890', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='usercode',
            field=models.CharField(default='ABC12345', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Ghana', max_length=255),
        ),
        migrations.DeleteModel(
            name='Ment',
        ),
    ]
