# Generated by Django 4.2.4 on 2023-08-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_medical_requested_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='drug_recommended',
            field=models.CharField(default='See Doctor', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medical',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, default='', upload_to='profile-uploads/'),
        ),
    ]
