# Generated by Django 4.2.4 on 2023-08-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_medical_drug_recommended_medical_recommended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical',
            name='drug_recommended',
        ),
    ]
