
questions = [
            "Do you experience any fever?",
            "Have you been vomiting lately?",
            "Are you experiencing chills without a fever?",
            "Do you feel shivering even in a warm environment?",
            "Do your hands and feet feel unusually cold?",
            "Do you have a persistent cough?",
            "Do you have frequent headache?",
            "Are you sweating more than usual?",
            "Do you feel nauseous often (nausea)?",
            "Is your heart rate faster than usual?",
            "Have you felt dizziness recently?",
            "Do you feel dehydrated even after drinking water?",
            "Is your urine darker in color?",
            "Are you experiencing back pain?",
            "Are you having diarrhoea?",
            "Do you feel itching internally?",
            "Do you experience pain in your belly?",
            "Have you noticed any changes in your appetite(loss of appetite)?",
            "Are you experiencing any pain or discomfort in your body?",
            "Do you have any joint stiffness or swelling?",
            "Have you been feeling fatigue or lacking energy?",
            "Are you having trouble sleeping or experiencing insomnia?",
            "Have you noticed any unusual weight loss or gain?",
            "Are you experiencing any chest pain or tightness?",
            "Do you have any breathing difficulties or shortness of breath?",
            "Are you having any problems with urination or bowel movements?",
            "Have you experienced any skin changes or rashes?",
            "Are you feeling excessively thirsty or experiencing frequent urination?",
            "Do you have any vision problems or changes in your eyesight?",
            "Are you feeling weak or experiencing muscle weakness?",
            "Are you experiencing muscle pain?",
            "Is there any joint pain you're currently feeling?",
            "Are you having stomach pain regularly?",
            "Do you have any difficulties with memory or concentration?"

        ]
